export const CONFIGURATOR_SET_DEFAULT_ACTIVE_ITEMS =
  'CONFIGURATOR_SET_DEFAULT_ACTIVE_ITEMS';
export const CONFIGURATOR_SET_ACTIVE_ITEMS = 'CONFIGURATOR_SET_ACTIVE_ITEMS';
export const CONFIGURATOR_SET_ACTIVE_ITEM_USER_SETTINGS =
  'CONFIGURATOR_SET_ACTIVE_ITEM_USER_SETTINGS';
export const CONFIGURATOR_SET_ACTIVE_CATEGORY =
  'CONFIGURATOR_SET_ACTIVE_CATEGORY';
export const CONFIGURATOR_OPEN_SUMMARY = 'CONFIGURATOR_OPEN_SUMMARY';
export const CONFIGURATOR_SAVED_PRODUCTS_TOGGLE =
  'CONFIGURATOR_SAVED_PRODUCTS_TOGGLE';
export const CONFIGURATOR_SAVED_PRODUCTS_OPEN =
  'CONFIGURATOR_SAVED_PRODUCTS_OPEN';
export const CONFIGURATOR_CHANGE_ACTIVE_ITEMS =
  'CONFIGURATOR_CHANGE_ACTIVE_ITEMS';
