export const CONFIGURATOR_SET_DEFAULT_ACTIVE_ITEMS =
  'CONFIGURATOR_SET_DEFAULT_ACTIVE_ITEMS';
export const CONFIGURATOR_SET_ACTIVE_ITEM = 'CONFIGURATOR_SET_ACTIVE_ITEM';
export const CONFIGURATOR_SET_ACTIVE_CATEGORY =
  'CONFIGURATOR_SET_ACTIVE_CATEGORY';
